# Demo: Creating and inspecting a narrative graph

This notebook will serve as a demo and small tour of some of the core functionalities of a `NarrativeGraph` object.

## Data setup

For this demo notebook, we will be using _News Category Dataset_ [1, 2] available on Kagglehub because it has short texts, timestamps and are categorized.

In [1]:
import time

from kagglehub import KaggleDatasetAdapter
import kagglehub

data = kagglehub.dataset_load(
    KaggleDatasetAdapter.PANDAS,
    "rmisra/news-category-dataset",
    "News_Category_Dataset_v3.json",
    pandas_kwargs=dict(lines=True),
)
data.head()

/Users/au479461/PycharmProjects/narrative-graph/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22

The columns that we will be using as input for our narrative graph.
- Documents: _headline_ + _short_description_
- IDs: link, but without the part that is in all of them
- Timestamps: _date_
- Categories: _category_

There are many categories. We will create a subset with just two of them: _U.S. News_ and _Politics_.

In [2]:
# create a sample
sample = data[data["category"].isin(["U.S. NEWS", "POLITICS"])].sample(
    5000, random_state=42
)
docs = sample["headline"] + "\n\n" + sample["short_description"]
ids = sample["link"].replace("https://www.huffpost.com/entry/", "")  # get rit of the first part of the URL
categories = sample["category"]
timestamps = sample["date"]

## Creating the model

Once we have our list of documents, which is the only required input, and extra metadata in aligned lists, we can create a narrative graph.

In [3]:
from narrativegraphs import NarrativeGraph

model = NarrativeGraph()
model.fit(docs, doc_ids=ids, categories=categories, timestamps=timestamps)

Extracting triplets: 100%|██████████| 5000/5000 [00:17<00:00, 289.17it/s]

## Inspecting the model visually

One of the key features of the _narrativegraphs_ package is that it lets a user inspect the output interactively in a browser-based visualizer. It is hosted directly on your machine by the Python package – no extra dependencies required. This is achieved with the one line below.

Click the link in the log messages to open in your browser.

In [4]:
# create server to be viewed in own browser which blocks execution of other cells
## model.serve_visualizer()

## Or run in the background
server = model.serve_visualizer(block=False)

INFO:     Started server process [1356]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8001 (Press CTRL+C to quit)
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1356]

In [5]:
server.stop()

Stop it by hitting the stop button on the cell in Jupyter Notebook or hit CTRL+C elsewhere.

## Inspecting and accessing the model programmatically

The graph consists of entities as nodes and their relations or cooccurrences as edges. These, along with the data that back them, like documents and extracted semantic triplets, can be retrieved from the model through properties or service attributes.

### Attributes

We can get the graph as a whole, as NetworkX graph, through the properties `.relation_graph_` and `.cooccurrence_graph_`.

In [6]:
relation_graph = model.relation_graph_

In [7]:
print(type(relation_graph))

<class 'networkx.classes.digraph.DiGraph'>

In [8]:
print(*list(relation_graph.nodes(data=True))[:3], sep="\n")

(1, {'id': 1, 'label': 'the early hours', 'frequency': 1, 'focus': False})
(2, {'id': 2, 'label': 'Election Day', 'frequency': 4, 'focus': False})
(3, {'id': 3, 'label': 'the ghost', 'frequency': 1, 'focus': False})

Similarly, entities and relations and everything else can be accessed as `pandas.DataFrame`s through properties.

In [9]:
model.entities_

,id,label,frequency,doc_frequency,adjusted_tf_idf,first_occurrence,last_occurrence,alt_labels,category
0,1,the early hours,1,1,0.0,2014-11-02,2014-11-02,[],[POLITICS]
1,2,Election Day,4,3,3750.0,2014-11-01,2016-09-28,[],"[POLITICS, POLITICS, POLITICS, POLITICS]"
2,3,the ghost,1,1,0.0,2014-11-02,2014-11-02,[],[POLITICS]
3,4,Election Day Past,1,1,0.0,2014-11-02,2014-11-02,[],[POLITICS]
4,5,Deportation Agents,1,1,0.0,2022-03-11,2022-03-11,[],[POLITICS]
...,...,...,...,...,...,...,...,...,...
7376,7377,Rank-and-file voters,1,1,0.0,2017-01-19,2017-01-19,[],[POLITICS]
7377,7378,Russian-aligned Wikileaks,1,1,0.0,2017-01-04,2017-01-04,[],[POLITICS]
7378,7379,the stage,1,1,0.0,2017-12-16,2017-12-16,[],[POLITICS]
7379,7380,James M. Dorsey US president Donald J. Trump’s...,1,1,0.0,2017-12-16,2017-12-16,[],[POLITICS]
7380,7381,Jerusalem,2,1,2500.0,2017-12-16,2017-12-16,[],"[POLITICS, POLITICS]"

The properties (with trailing `_`) are nice in that they give back the data in well-known formats that one can continue working with, e.g. NetworkX graphs for graph algorithms and DataFrames for statistical analyses.

### Service attributes

However, the service attributes offer more control and may be especially handy if the model is quite big, so that you do not necessarily want everything spit out at once.

For instance, you can search for entities with the `entities` service.

In [10]:
democrats_matches = model.entities.search("democrats")
democrats_matches[:10]

[EntityLabel(id=240, label='Democrats'),
 EntityLabel(id=5186, label="Democrats' Rebuttal"),
 EntityLabel(id=3255, label="Democrats' big reform bill"),
 EntityLabel(id=1202, label='House Democrats'),
 EntityLabel(id=1969, label='U.S. Democrats'),
 EntityLabel(id=2492, label='Senate Democrats'),
 EntityLabel(id=308, label='Two Democrats'),
 EntityLabel(id=1353, label='2016 Democrats'),
 EntityLabel(id=401, label='Iowa Democrats'),
 EntityLabel(id=6415, label='Taunt Democrats')]

In [11]:
democrats_id = democrats_matches[0].id

And you can create a subgraph that expands from a set of focus nodes and only includes those that pass a filter.

In [12]:
from datetime import date
from narrativegraphs import GraphFilter

democrats_graph = model.graph.expand_from_focus_entities(
    [democrats_id],
    "relation",
    graph_filter=GraphFilter(
        categories={'category': ["POLITICS"]},
        earliest_date=date(2014, 1, 1)
    )
)

# stripping labels to remove some whitespaces
print("NODES")
for node in democrats_graph.nodes:
    print(node.id, node.label.strip())

print("\nEDGES")
for edge in democrats_graph.edges:
    print(edge.subject_label.strip(), '--', edge.label, '->', edge.object_label.strip())

NODES
240 Democrats
241 a majority
242 Republicans Flip Virginia House
409 Obama
479 Senate
762 A Landslide
892 Trump Voters
906 Bill
1035 More GOP-Held State House Seats
1080 different findings
1082 This committee
1253 good news
1454 Calls
1497 Tehran
1545 judicial nominee Steven Menashi
1574 the Ohio Republican's slam
1632 a bitter partisan battle
1652 This Billionaire Environmental Activist
1967 Key States
2022 Pennsylvania Republican
2112 Republican Lt. Gov. Kim Guadagno
2388 the ballot box
2389 Special Election
2390 Resources
2689 More Clarity
2920 Eyeing 2018 Senate Takeover
3033 Little Time
3070 Inaugural Address Worthy
3178 Hugh Hewitt
3481 The Longest-Serving Woman
3836 Hemp
4052 Nationwide Day
4216 Black candidates
4263 a scapegoat
4394 For Independent Commission
4485 More Than A Dozen State Legislative Chambers
4696 Rep. Ruben Kihuen
4811 Renewed Push
4914 Oversight Committee
5235 Their Nadir
5323 Investigations
5698 Probe
6424 Roughly 40 percent
6430 Short But Outperform Expectations
6711 Biden's Decision
6753 Trump's Voter Fraud Investigation
6917 Suspected Russian Role
7319 their worst electoral position

EDGES
Democrats -- conceded -> a majority
Democrats -- needs -> Trump Voters
Democrats -- advanced, Calls -> Bill
Democrats -- Flip -> More GOP-Held State House Seats
Democrats -- Has -> different findings
Democrats -- on -> This committee
Democrats -- asked -> judicial nominee Steven Menashi
Democrats -- Defeated -> Republican Lt. Gov. Kim Guadagno
Democrats -- won -> Special Election
Democrats -- dominated -> the ballot box
Democrats -- Pumped -> Resources
Democrats -- Demands -> More Clarity
Democrats -- Begin -> Eyeing 2018 Senate Takeover
Democrats -- fled -> Obama
Democrats -- led -> Key States
Democrats -- Has -> Little Time
Democrats -- for -> Senate
Democrats -- Became -> The Longest-Serving Woman
Democrats -- Agree -> Hemp
Democrats -- led -> Nationwide Day
Democrats -- nominate -> Black candidates
Democrats -- Renew -> Calls
Democrats -- cast -> a scapegoat
Democrats -- Push -> For Independent Commission
Democrats -- won -> More Than A Dozen State Legislative Chambers
Democrats -- Calls -> Rep. Ruben Kihuen
Democrats -- made -> Renewed Push
Democrats -- asked -> Oversight Committee
Democrats -- needs -> A Landslide
Democrats -- is -> Their Nadir
Democrats -- Calls -> Probe
Democrats -- Want -> Investigations
Democrats -- Comes -> Short But Outperform Expectations
Democrats -- Supporting -> Biden's Decision
Democrats -- Participating -> Trump's Voter Fraud Investigation
Democrats -- of -> Suspected Russian Role
Democrats -- is -> their worst electoral position
a majority -- of -> Democrats
a majority -- in -> Senate
Republicans Flip Virginia House -- to -> Democrats
good news -- for -> Democrats
Tehran -- see -> Democrats
the Ohio Republican's slam -- of -> Democrats
a bitter partisan battle -- With -> Democrats
This Billionaire Environmental Activist -- picked -> Democrats
Pennsylvania Republican -- Want -> Democrats
Inaugural Address Worthy -- of -> Democrats
Hugh Hewitt -- Backs -> Democrats
Roughly 40 percent -- of -> Democrats

### Saving and loading the model

We can save the model for later use, especially if we have a lot of documents that takes a while to process.

In [13]:
model.save_to_file("demo.db", overwrite=True)

And we can load it from that saved file.

In [14]:
model = NarrativeGraph.load("demo")

## References

[1] Misra, Rishabh. "News Category Dataset." arXiv preprint arXiv:2209.11429 (2022).

[2] Misra, Rishabh and Jigyasa Grover. "Sculpting Data for ML: The first act of Machine Learning." ISBN 9798585463570 (2021).